const router=require("express").Router()
const { usersinup, login, getallfriendsusers, singleuserget, getallusers, getallfriendsusersd, updateprofile } = require("../controllers/Users")
const { authenticate } = require("../middlewate/auth")
const {chatmessage, getchatmessage, redisapi} =require("../controllers/Chat")
const { otpverify, otpsend } = require("../controllers/Otp")
const { upload } = require("../middlewate/fileupload")
const { requestSend, requestAccpect,  checkAccpection } = require("../controllers/requestverification")
const { userBlock, userUnblock, getBlockuser } = require("../controllers/blockusers")

router.post("/sinup",upload.single('profile'),usersinup)
router.post("/login",login)
router.post("/msgcreate", upload.single('img'),chatmessage)
router.post("/allfriendsd",getallfriendsusersd)
router.post("/allfriends",getallfriendsusers)
router.post("/getmessage",getchatmessage)
router.get('/singleuser',authenticate,singleuserget)
router.get('/allusers',authenticate,getallusers)
router.post('/sendotp',otpsend)
router.post('/otpverify',otpverify)
router.post('/requestsend',authenticate,requestSend)
router.post('/requestaccpect',authenticate,requestAccpect)
router.post('/userblock',authenticate,userBlock)
router.post('/unblock',authenticate,userUnblock)
router.post('/checkAccetion',authenticate,checkAccpection)
router.post('/getblockuser',authenticate,getBlockuser)
router.post('/redis',authenticate,redisapi)
router.put('/updateprofile',upload.single('img'),updateprofile)
module.exports=router